### PR TITLE
Localization

### PR DESCRIPTION
**Pull request by ecc521**
Merge localization code into master

### CODE REVIEW

**Review by Miles-Mom — APPROVED** [review]

**Comment by ecc521** [comment]
Work still underway on this one - See progress in #99

**Review by Miles-Mom — APPROVED** [review]

**Review by Miles-Mom — APPROVED** [review]
Just noticed an amiss of mine in your last change roomManager.js, we need to do the 
let roomId = "Offline"
	let nickname = nicknameInput.value || "Player 1"
to i18n.__(the room, the player1 name)... 

If it is easy for you to change, here are the locales, you can add to zh.json around line 87
	"Offline" : "下线桌子",
	"Player 1":"第一家",

If not, I can put them in. I am sure there are stragglers like these. Sorry about all these.

**Comment by ecc521** [comment]
Ah - good catch. I'll get that fixed.

**Comment by Miles-Mom** [comment]
"Offline" : "下线",
"Player 1":"第一家",

Otherwise the Room/桌子 clashes with the concatenated room...

**Comment by Miles-Mom** [comment]
Offline messaging should work.. I've tested it.. unless i messed up something.

**Comment by ecc521** [comment]
@Miles-Mom 
I messed up the offline messaging fixing a different item. It is fixed now.

**Pull request merged**
