### PR TITLE
Update reload-icon.svg

### PR DESCRIPTION
**Pull request by Miles-Mom**
simple direction change of the reload icon, to be the same as the playing. thus baby-step relearning git.

### CODE REVIEW

**Comment by ecc521** [comment]
Alright - some legal stuff:
I'm going to need rights to your contributions to redistribute them, etc. I've added a PR template that will appear in the future - as for now, I'll link you to the template to fill out.

**Comment by ecc521** [comment]
Please see https://github.com/ecc521/mahjong/blob/master/.github/pull_request_template.md for the new PR template. I'd recommend copying & pasting then filling out the contributor agreement.

**Comment by Miles-Mom** [comment]
Ack
[011422 Reload Button Change Pull Request Contribution Agreement.docx](https://github.com/ecc521/mahjong/files/7873828/011422.Reload.Button.Change.Pull.Request.Contribution.Agreement.docx)
.

**Comment by ecc521** [comment]
I'm not sure I like the arrow being on the bottom rather than the top, but I'll go with it for now.

**Comment by ecc521** [comment]
Yep - please ignore the reversion above. Just rotated the button to look like: 
Screen Shot 2022-01-15 at 6 34 25 PM

**Comment by ecc521** [comment]
Since this is an incredibly minor change, I'll batch it with whatever comes out next.

**Comment by Miles-Mom** [comment]
I like your on-top version myself. In addition to more pleasing, the arrow
starts with East, which is more natural for Chinese mahjong also.

Also, I like the issues list on GitHub!

Thanks!

**Pull request merged**
