### PR TITLE
Extensive translation refinement, fixed one minor JoinGame bug

### PR DESCRIPTION
**Pull request by Miles-Mom**
## Pull Request Details

- [x ] I agree to the Contributor Agreement (located in [contributing.md](../contributing.md))

### CODE REVIEW

**Comment by Miles-Mom** [comment]
@ecc521 Please review if the perceived bug was my git problem or real. 

* On the GoMahjong! action button, I took one user suggestion of adding a winner emoji, to make it clear, as different region has different dialect, and I insisting on the good Luck Fu - rather than the more usually beard/Hu or porridge/Hu, to go with our lucky brand name HeJaFu (whole family friends luck). This change would show on the game room, as well as the final scoring page. If you don't like it, just remove it. 

* There were several "East Wind" reference in verbiages, we translated them to "East Seat" player, which I think is the case, it is not the East Wind as the tile, and in Chinese the seating does not comes with the wind reference. I am not sure if the American/other styles call the seats Winds or if that was a typo. FYI. 

* The Google store App behaved better today. It was rather erratic earlier. 

The bulk of the review should be done. Continued testing/improvement aside.

Thanks. ( I am going to try to find out how to link the issue to this pull...)

**Comment by ecc521** [comment]
Google app issue is fixed. There was an update rolling out.

**Comment by Miles-Mom** [comment]
@ecc521 recalling your email of your initial verbiage concerns prompted me to make most recent translation change [5c5635e](https://github.com/ecc521/mahjong/pull/118/commits/5c5635e6a0303b3e67cfe7ccdc0efaa70fc28c0e). We went back to the more colloquial "table" 桌子 reference, and not the more formal/grand "card table"牌桌 reference. The concern was with the Chinese firewall scanning etc. Best to stay on the benevolent side, as we are.

**Review by ecc521 — CHANGES_REQUESTED** [review]
See comment - I'd like to understand the server.js changes.

**Comment by Miles-Mom** [comment]
Here is how to duplicate: if you enter a room name that does not exist, a
message is suppose to come up, but if the obj.locale is not set, which
seems to be the case at a non-restored user ?session, the i18n errors out,
so nothing happens, no message, nada.

( If would be nicer if the library itself would take its default locale
even if the explicit locale is requested, which is in our server usage
case, at least not errors out, but that'll have to wait another day)

**Comment by Miles-Mom** [comment]
Replicate.

**Comment by ecc521** [comment]
@Miles-Mom 
I found the issue. I'll make sure it's fixed.

**Comment by ecc521** [comment]
Alright - all merged.
There was a much easier fix (see 640b58b) - it was a simple switch between obj.locale and client.locale

**Comment by Miles-Mom** [comment]
I had thought there was some special way that a joinRoom can be called
through the restored saved file path, and that's why you had to change it
to obj.locale?

**Comment by ecc521** [comment]
I fixed some save file bugs by setting client.locale in getCurrentRoom
instead.

So obj.locale is not sent for joinRoom anymore.

**Comment by Miles-Mom** [comment]
Thanks!! I was still trying to figure it out, and this note helped :)).
just didn't want us to lose that change, for it was rather involved I
recall.

**Pull request merged**
